### ISSUE TITLE
The commit author name change after installing your dotfile ...

### ISSUE THREAD

**Issue by evah** [PytLab/dotfiles#1]
I do not know how it happened... 
After I install your dotfiles using `./setup --install` my local git commit author becomes **Pytlab**. 
Could you fix that bug in your installation script?

**Comment by PytLab** [comment]
this problem is caused by the creation of the symlink of MY `.gitconfig` file to your `$HOME/`. You can solve this problem by changing the content in `YOURPATH/dotfile/.gitconfig` and reinstalling it again.
I'll add more informations in the installation part in README about symlink creation of the configure files of MY OWN. Thanks

**Comment by evah** [comment]
Thanks! Later when I realize it, I manually changed it back. Your setting is really handy and elegant. Is there a way to not hard-code those parameters into .gitconfig but ask for an input or something?

**Comment by PytLab** [comment]
Actually, this repository was just for my personal use at first. Yes. I will add some input parameter settings later and update  the setup script for more general use. :)
